version: "3"
services:
  my-web-app-db:
    image: mysql
    ports:
    - "3307:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=refrezherator
      - MYSQL_DATABASE=food_products
    restart: always
  my-web-app:
    build: .
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - my-web-app-db
#  nginx:
#    image: nginx:1.17-alpine
#    container_name: nginx
#    volumes:
#    - ./default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - my-web-app