-- MySQL Script generated by MySQL Workbench
-- Fri Oct 15 17:51:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_products
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_products` DEFAULT CHARACTER SET utf8 ;
USE `food_products` ;

-- -----------------------------------------------------
-- Table `food_products`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`categories` (
    `id` INT NOT NULL,
    `name` VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`hibernate_sequence` (
    `next_val` BIGINT NULL DEFAULT NULL)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`products` (
    `id` INT NOT NULL,
    `name` VARCHAR(45) NULL DEFAULT NULL,
    `category_id` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `3_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `3`
    FOREIGN KEY (`category_id`)
    REFERENCES `food_products`.`categories` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`roles` (
    `id` INT NOT NULL,
    `name` VARCHAR(15) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`shops` (
    `id` INT NOT NULL,
    `name` VARCHAR(25) NULL DEFAULT NULL,
    `address` VARCHAR(70) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`shops_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`shops_products` (
    `id` INT NOT NULL,
    `shop_id` INT NULL DEFAULT NULL,
    `product_id` INT NULL DEFAULT NULL,
    `cost` DOUBLE NULL DEFAULT NULL,
    `date` DATE NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `4_idx` (`shop_id` ASC) VISIBLE,
    INDEX `5_idx` (`product_id` ASC) VISIBLE,
    CONSTRAINT `4`
    FOREIGN KEY (`shop_id`)
    REFERENCES `food_products`.`shops` (`id`),
    CONSTRAINT `5`
    FOREIGN KEY (`product_id`)
    REFERENCES `food_products`.`products` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`users` (
    `id` INT NOT NULL,
    `name` VARCHAR(20) NULL DEFAULT NULL,
    `surname` VARCHAR(20) NULL DEFAULT NULL,
    `login` VARCHAR(20) NULL DEFAULT NULL,
    `password` VARCHAR(70) NULL DEFAULT NULL,
    `phone` VARCHAR(15) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `food_products`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_products`.`users_roles` (
    `User_id` INT NOT NULL,
    `roles_id` INT NOT NULL,
    PRIMARY KEY (`User_id`, `roles_id`),
    INDEX `FKa62j07k5mhgifpp955h37ponj` (`roles_id` ASC) VISIBLE,
    CONSTRAINT `FKa62j07k5mhgifpp955h37ponj`
    FOREIGN KEY (`roles_id`)
    REFERENCES `food_products`.`roles` (`id`),
    CONSTRAINT `FKe6k7h92pkxjim6t1176b7h95x`
    FOREIGN KEY (`User_id`)
    REFERENCES `food_products`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
